/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
)

// Linger please
var (
	_ _context.Context
)

// NWDAFAnalyticsDocumentApiService NWDAFAnalyticsDocumentApi service
type NWDAFAnalyticsDocumentApiService service

type ApiGetNWDAFAnalyticsRequest struct {
	ctx _context.Context
	ApiService *NWDAFAnalyticsDocumentApiService
	eventId *EventId
	anaReq *EventReportingRequirement
	eventFilter *EventFilter
	supportedFeatures *map[string]interface{}
	tgtUe *map[string]interface{}
}

func (r ApiGetNWDAFAnalyticsRequest) EventId(eventId EventId) ApiGetNWDAFAnalyticsRequest {
	r.eventId = &eventId
	return r
}
func (r ApiGetNWDAFAnalyticsRequest) AnaReq(anaReq EventReportingRequirement) ApiGetNWDAFAnalyticsRequest {
	r.anaReq = &anaReq
	return r
}
func (r ApiGetNWDAFAnalyticsRequest) EventFilter(eventFilter EventFilter) ApiGetNWDAFAnalyticsRequest {
	r.eventFilter = &eventFilter
	return r
}
func (r ApiGetNWDAFAnalyticsRequest) SupportedFeatures(supportedFeatures map[string]interface{}) ApiGetNWDAFAnalyticsRequest {
	r.supportedFeatures = &supportedFeatures
	return r
}
func (r ApiGetNWDAFAnalyticsRequest) TgtUe(tgtUe map[string]interface{}) ApiGetNWDAFAnalyticsRequest {
	r.tgtUe = &tgtUe
	return r
}

func (r ApiGetNWDAFAnalyticsRequest) Execute() (AnalyticsData, *_nethttp.Response, GenericOpenAPIError) {
	return r.ApiService.GetNWDAFAnalyticsExecute(r)
}

/*
 * GetNWDAFAnalytics Read a NWDAF Analytics
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiGetNWDAFAnalyticsRequest
 */
func (a *NWDAFAnalyticsDocumentApiService) GetNWDAFAnalytics(ctx _context.Context) ApiGetNWDAFAnalyticsRequest {
	return ApiGetNWDAFAnalyticsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

/*
 * Execute executes the request
 * @return AnalyticsData
 */
func (a *NWDAFAnalyticsDocumentApiService) GetNWDAFAnalyticsExecute(r ApiGetNWDAFAnalyticsRequest) (AnalyticsData, *_nethttp.Response, GenericOpenAPIError) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		executionError       GenericOpenAPIError
		localVarReturnValue  AnalyticsData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NWDAFAnalyticsDocumentApiService.GetNWDAFAnalytics")
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, nil, executionError
	}

	localVarPath := localBasePath + "/analytics"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.eventId == nil {
		executionError.error = "eventId is required and must be specified"
		return localVarReturnValue, nil, executionError
	}

	localVarQueryParams.Add("event-id", parameterToString(*r.eventId, ""))
	if r.anaReq != nil {
		localVarQueryParams.Add("ana-req", parameterToString(*r.anaReq, ""))
	}
	if r.eventFilter != nil {
		localVarQueryParams.Add("event-filter", parameterToString(*r.eventFilter, ""))
	}
	if r.supportedFeatures != nil {
		localVarQueryParams.Add("supported-features", parameterToString(*r.supportedFeatures, ""))
	}
	if r.tgtUe != nil {
		localVarQueryParams.Add("tgt-ue", parameterToString(*r.tgtUe, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, nil, executionError
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		executionError.error = err.Error()
		return localVarReturnValue, localVarHTTPResponse, executionError
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, localVarHTTPResponse, executionError
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v map[string]interface{}
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, executionError
}
