/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EventFilter struct for EventFilter
type EventFilter struct {
	AnySlice *map[string]interface{} `json:"anySlice,omitempty"`
	// Identification(s) of network slice to which the subscription belongs.
	Snssais *[]map[string]interface{} `json:"snssais,omitempty"`
	AppIds *[]map[string]interface{} `json:"appIds,omitempty"`
	Dnns *[]map[string]interface{} `json:"dnns,omitempty"`
	Dnais *[]map[string]interface{} `json:"dnais,omitempty"`
	NetworkArea *map[string]interface{} `json:"networkArea,omitempty"`
	NfInstanceIds *[]map[string]interface{} `json:"nfInstanceIds,omitempty"`
	NfSetIds *[]map[string]interface{} `json:"nfSetIds,omitempty"`
	NfTypes *[]map[string]interface{} `json:"nfTypes,omitempty"`
	NsiIdInfos *[]map[string]interface{} `json:"nsiIdInfos,omitempty"`
	QosRequ *map[string]interface{} `json:"qosRequ,omitempty"`
	NwPerfTypes *[]map[string]interface{} `json:"nwPerfTypes,omitempty"`
	BwRequs *[]map[string]interface{} `json:"bwRequs,omitempty"`
	ExcepIds *[]map[string]interface{} `json:"excepIds,omitempty"`
	ExptAnaType *map[string]interface{} `json:"exptAnaType,omitempty"`
	ExptUeBehav *map[string]interface{} `json:"exptUeBehav,omitempty"`
}

// NewEventFilter instantiates a new EventFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventFilter() *EventFilter {
	this := EventFilter{}
	return &this
}

// NewEventFilterWithDefaults instantiates a new EventFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventFilterWithDefaults() *EventFilter {
	this := EventFilter{}
	return &this
}

// GetAnySlice returns the AnySlice field value if set, zero value otherwise.
func (o *EventFilter) GetAnySlice() map[string]interface{} {
	if o == nil || o.AnySlice == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.AnySlice
}

// GetAnySliceOk returns a tuple with the AnySlice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetAnySliceOk() (*map[string]interface{}, bool) {
	if o == nil || o.AnySlice == nil {
		return nil, false
	}
	return o.AnySlice, true
}

// HasAnySlice returns a boolean if a field has been set.
func (o *EventFilter) HasAnySlice() bool {
	if o != nil && o.AnySlice != nil {
		return true
	}

	return false
}

// SetAnySlice gets a reference to the given map[string]interface{} and assigns it to the AnySlice field.
func (o *EventFilter) SetAnySlice(v map[string]interface{}) {
	o.AnySlice = &v
}

// GetSnssais returns the Snssais field value if set, zero value otherwise.
func (o *EventFilter) GetSnssais() []map[string]interface{} {
	if o == nil || o.Snssais == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Snssais
}

// GetSnssaisOk returns a tuple with the Snssais field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetSnssaisOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Snssais == nil {
		return nil, false
	}
	return o.Snssais, true
}

// HasSnssais returns a boolean if a field has been set.
func (o *EventFilter) HasSnssais() bool {
	if o != nil && o.Snssais != nil {
		return true
	}

	return false
}

// SetSnssais gets a reference to the given []map[string]interface{} and assigns it to the Snssais field.
func (o *EventFilter) SetSnssais(v []map[string]interface{}) {
	o.Snssais = &v
}

// GetAppIds returns the AppIds field value if set, zero value otherwise.
func (o *EventFilter) GetAppIds() []map[string]interface{} {
	if o == nil || o.AppIds == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.AppIds
}

// GetAppIdsOk returns a tuple with the AppIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetAppIdsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.AppIds == nil {
		return nil, false
	}
	return o.AppIds, true
}

// HasAppIds returns a boolean if a field has been set.
func (o *EventFilter) HasAppIds() bool {
	if o != nil && o.AppIds != nil {
		return true
	}

	return false
}

// SetAppIds gets a reference to the given []map[string]interface{} and assigns it to the AppIds field.
func (o *EventFilter) SetAppIds(v []map[string]interface{}) {
	o.AppIds = &v
}

// GetDnns returns the Dnns field value if set, zero value otherwise.
func (o *EventFilter) GetDnns() []map[string]interface{} {
	if o == nil || o.Dnns == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Dnns
}

// GetDnnsOk returns a tuple with the Dnns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetDnnsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Dnns == nil {
		return nil, false
	}
	return o.Dnns, true
}

// HasDnns returns a boolean if a field has been set.
func (o *EventFilter) HasDnns() bool {
	if o != nil && o.Dnns != nil {
		return true
	}

	return false
}

// SetDnns gets a reference to the given []map[string]interface{} and assigns it to the Dnns field.
func (o *EventFilter) SetDnns(v []map[string]interface{}) {
	o.Dnns = &v
}

// GetDnais returns the Dnais field value if set, zero value otherwise.
func (o *EventFilter) GetDnais() []map[string]interface{} {
	if o == nil || o.Dnais == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Dnais
}

// GetDnaisOk returns a tuple with the Dnais field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetDnaisOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Dnais == nil {
		return nil, false
	}
	return o.Dnais, true
}

// HasDnais returns a boolean if a field has been set.
func (o *EventFilter) HasDnais() bool {
	if o != nil && o.Dnais != nil {
		return true
	}

	return false
}

// SetDnais gets a reference to the given []map[string]interface{} and assigns it to the Dnais field.
func (o *EventFilter) SetDnais(v []map[string]interface{}) {
	o.Dnais = &v
}

// GetNetworkArea returns the NetworkArea field value if set, zero value otherwise.
func (o *EventFilter) GetNetworkArea() map[string]interface{} {
	if o == nil || o.NetworkArea == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.NetworkArea
}

// GetNetworkAreaOk returns a tuple with the NetworkArea field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetNetworkAreaOk() (*map[string]interface{}, bool) {
	if o == nil || o.NetworkArea == nil {
		return nil, false
	}
	return o.NetworkArea, true
}

// HasNetworkArea returns a boolean if a field has been set.
func (o *EventFilter) HasNetworkArea() bool {
	if o != nil && o.NetworkArea != nil {
		return true
	}

	return false
}

// SetNetworkArea gets a reference to the given map[string]interface{} and assigns it to the NetworkArea field.
func (o *EventFilter) SetNetworkArea(v map[string]interface{}) {
	o.NetworkArea = &v
}

// GetNfInstanceIds returns the NfInstanceIds field value if set, zero value otherwise.
func (o *EventFilter) GetNfInstanceIds() []map[string]interface{} {
	if o == nil || o.NfInstanceIds == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.NfInstanceIds
}

// GetNfInstanceIdsOk returns a tuple with the NfInstanceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetNfInstanceIdsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.NfInstanceIds == nil {
		return nil, false
	}
	return o.NfInstanceIds, true
}

// HasNfInstanceIds returns a boolean if a field has been set.
func (o *EventFilter) HasNfInstanceIds() bool {
	if o != nil && o.NfInstanceIds != nil {
		return true
	}

	return false
}

// SetNfInstanceIds gets a reference to the given []map[string]interface{} and assigns it to the NfInstanceIds field.
func (o *EventFilter) SetNfInstanceIds(v []map[string]interface{}) {
	o.NfInstanceIds = &v
}

// GetNfSetIds returns the NfSetIds field value if set, zero value otherwise.
func (o *EventFilter) GetNfSetIds() []map[string]interface{} {
	if o == nil || o.NfSetIds == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.NfSetIds
}

// GetNfSetIdsOk returns a tuple with the NfSetIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetNfSetIdsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.NfSetIds == nil {
		return nil, false
	}
	return o.NfSetIds, true
}

// HasNfSetIds returns a boolean if a field has been set.
func (o *EventFilter) HasNfSetIds() bool {
	if o != nil && o.NfSetIds != nil {
		return true
	}

	return false
}

// SetNfSetIds gets a reference to the given []map[string]interface{} and assigns it to the NfSetIds field.
func (o *EventFilter) SetNfSetIds(v []map[string]interface{}) {
	o.NfSetIds = &v
}

// GetNfTypes returns the NfTypes field value if set, zero value otherwise.
func (o *EventFilter) GetNfTypes() []map[string]interface{} {
	if o == nil || o.NfTypes == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.NfTypes
}

// GetNfTypesOk returns a tuple with the NfTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetNfTypesOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.NfTypes == nil {
		return nil, false
	}
	return o.NfTypes, true
}

// HasNfTypes returns a boolean if a field has been set.
func (o *EventFilter) HasNfTypes() bool {
	if o != nil && o.NfTypes != nil {
		return true
	}

	return false
}

// SetNfTypes gets a reference to the given []map[string]interface{} and assigns it to the NfTypes field.
func (o *EventFilter) SetNfTypes(v []map[string]interface{}) {
	o.NfTypes = &v
}

// GetNsiIdInfos returns the NsiIdInfos field value if set, zero value otherwise.
func (o *EventFilter) GetNsiIdInfos() []map[string]interface{} {
	if o == nil || o.NsiIdInfos == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.NsiIdInfos
}

// GetNsiIdInfosOk returns a tuple with the NsiIdInfos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetNsiIdInfosOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.NsiIdInfos == nil {
		return nil, false
	}
	return o.NsiIdInfos, true
}

// HasNsiIdInfos returns a boolean if a field has been set.
func (o *EventFilter) HasNsiIdInfos() bool {
	if o != nil && o.NsiIdInfos != nil {
		return true
	}

	return false
}

// SetNsiIdInfos gets a reference to the given []map[string]interface{} and assigns it to the NsiIdInfos field.
func (o *EventFilter) SetNsiIdInfos(v []map[string]interface{}) {
	o.NsiIdInfos = &v
}

// GetQosRequ returns the QosRequ field value if set, zero value otherwise.
func (o *EventFilter) GetQosRequ() map[string]interface{} {
	if o == nil || o.QosRequ == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.QosRequ
}

// GetQosRequOk returns a tuple with the QosRequ field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetQosRequOk() (*map[string]interface{}, bool) {
	if o == nil || o.QosRequ == nil {
		return nil, false
	}
	return o.QosRequ, true
}

// HasQosRequ returns a boolean if a field has been set.
func (o *EventFilter) HasQosRequ() bool {
	if o != nil && o.QosRequ != nil {
		return true
	}

	return false
}

// SetQosRequ gets a reference to the given map[string]interface{} and assigns it to the QosRequ field.
func (o *EventFilter) SetQosRequ(v map[string]interface{}) {
	o.QosRequ = &v
}

// GetNwPerfTypes returns the NwPerfTypes field value if set, zero value otherwise.
func (o *EventFilter) GetNwPerfTypes() []map[string]interface{} {
	if o == nil || o.NwPerfTypes == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.NwPerfTypes
}

// GetNwPerfTypesOk returns a tuple with the NwPerfTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetNwPerfTypesOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.NwPerfTypes == nil {
		return nil, false
	}
	return o.NwPerfTypes, true
}

// HasNwPerfTypes returns a boolean if a field has been set.
func (o *EventFilter) HasNwPerfTypes() bool {
	if o != nil && o.NwPerfTypes != nil {
		return true
	}

	return false
}

// SetNwPerfTypes gets a reference to the given []map[string]interface{} and assigns it to the NwPerfTypes field.
func (o *EventFilter) SetNwPerfTypes(v []map[string]interface{}) {
	o.NwPerfTypes = &v
}

// GetBwRequs returns the BwRequs field value if set, zero value otherwise.
func (o *EventFilter) GetBwRequs() []map[string]interface{} {
	if o == nil || o.BwRequs == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.BwRequs
}

// GetBwRequsOk returns a tuple with the BwRequs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetBwRequsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.BwRequs == nil {
		return nil, false
	}
	return o.BwRequs, true
}

// HasBwRequs returns a boolean if a field has been set.
func (o *EventFilter) HasBwRequs() bool {
	if o != nil && o.BwRequs != nil {
		return true
	}

	return false
}

// SetBwRequs gets a reference to the given []map[string]interface{} and assigns it to the BwRequs field.
func (o *EventFilter) SetBwRequs(v []map[string]interface{}) {
	o.BwRequs = &v
}

// GetExcepIds returns the ExcepIds field value if set, zero value otherwise.
func (o *EventFilter) GetExcepIds() []map[string]interface{} {
	if o == nil || o.ExcepIds == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.ExcepIds
}

// GetExcepIdsOk returns a tuple with the ExcepIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetExcepIdsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.ExcepIds == nil {
		return nil, false
	}
	return o.ExcepIds, true
}

// HasExcepIds returns a boolean if a field has been set.
func (o *EventFilter) HasExcepIds() bool {
	if o != nil && o.ExcepIds != nil {
		return true
	}

	return false
}

// SetExcepIds gets a reference to the given []map[string]interface{} and assigns it to the ExcepIds field.
func (o *EventFilter) SetExcepIds(v []map[string]interface{}) {
	o.ExcepIds = &v
}

// GetExptAnaType returns the ExptAnaType field value if set, zero value otherwise.
func (o *EventFilter) GetExptAnaType() map[string]interface{} {
	if o == nil || o.ExptAnaType == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.ExptAnaType
}

// GetExptAnaTypeOk returns a tuple with the ExptAnaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetExptAnaTypeOk() (*map[string]interface{}, bool) {
	if o == nil || o.ExptAnaType == nil {
		return nil, false
	}
	return o.ExptAnaType, true
}

// HasExptAnaType returns a boolean if a field has been set.
func (o *EventFilter) HasExptAnaType() bool {
	if o != nil && o.ExptAnaType != nil {
		return true
	}

	return false
}

// SetExptAnaType gets a reference to the given map[string]interface{} and assigns it to the ExptAnaType field.
func (o *EventFilter) SetExptAnaType(v map[string]interface{}) {
	o.ExptAnaType = &v
}

// GetExptUeBehav returns the ExptUeBehav field value if set, zero value otherwise.
func (o *EventFilter) GetExptUeBehav() map[string]interface{} {
	if o == nil || o.ExptUeBehav == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.ExptUeBehav
}

// GetExptUeBehavOk returns a tuple with the ExptUeBehav field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventFilter) GetExptUeBehavOk() (*map[string]interface{}, bool) {
	if o == nil || o.ExptUeBehav == nil {
		return nil, false
	}
	return o.ExptUeBehav, true
}

// HasExptUeBehav returns a boolean if a field has been set.
func (o *EventFilter) HasExptUeBehav() bool {
	if o != nil && o.ExptUeBehav != nil {
		return true
	}

	return false
}

// SetExptUeBehav gets a reference to the given map[string]interface{} and assigns it to the ExptUeBehav field.
func (o *EventFilter) SetExptUeBehav(v map[string]interface{}) {
	o.ExptUeBehav = &v
}

func (o EventFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AnySlice != nil {
		toSerialize["anySlice"] = o.AnySlice
	}
	if o.Snssais != nil {
		toSerialize["snssais"] = o.Snssais
	}
	if o.AppIds != nil {
		toSerialize["appIds"] = o.AppIds
	}
	if o.Dnns != nil {
		toSerialize["dnns"] = o.Dnns
	}
	if o.Dnais != nil {
		toSerialize["dnais"] = o.Dnais
	}
	if o.NetworkArea != nil {
		toSerialize["networkArea"] = o.NetworkArea
	}
	if o.NfInstanceIds != nil {
		toSerialize["nfInstanceIds"] = o.NfInstanceIds
	}
	if o.NfSetIds != nil {
		toSerialize["nfSetIds"] = o.NfSetIds
	}
	if o.NfTypes != nil {
		toSerialize["nfTypes"] = o.NfTypes
	}
	if o.NsiIdInfos != nil {
		toSerialize["nsiIdInfos"] = o.NsiIdInfos
	}
	if o.QosRequ != nil {
		toSerialize["qosRequ"] = o.QosRequ
	}
	if o.NwPerfTypes != nil {
		toSerialize["nwPerfTypes"] = o.NwPerfTypes
	}
	if o.BwRequs != nil {
		toSerialize["bwRequs"] = o.BwRequs
	}
	if o.ExcepIds != nil {
		toSerialize["excepIds"] = o.ExcepIds
	}
	if o.ExptAnaType != nil {
		toSerialize["exptAnaType"] = o.ExptAnaType
	}
	if o.ExptUeBehav != nil {
		toSerialize["exptUeBehav"] = o.ExptUeBehav
	}
	return json.Marshal(toSerialize)
}

type NullableEventFilter struct {
	value *EventFilter
	isSet bool
}

func (v NullableEventFilter) Get() *EventFilter {
	return v.value
}

func (v *NullableEventFilter) Set(val *EventFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableEventFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableEventFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventFilter(val *EventFilter) *NullableEventFilter {
	return &NullableEventFilter{value: val, isSet: true}
}

func (v NullableEventFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


