openapi: 3.0.0
info:
  description: |
    Nnwdaf_AnalyticsInfo Service API.
    © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
  title: Nnwdaf_AnalyticsInfo
  version: 1.2.0-alpha.1
externalDocs:
  description: 3GPP TS 29.520 V17.1.0; 5G System; Network Data Analytics Services.
  url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.520/
servers:
- url: '{apiRoot}/nnwdaf-analyticsinfo/v1'
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501.
security:
- {}
- oAuth2ClientCredentials:
  - nnwdaf-analyticsinfo
paths:
  /analytics:
    get:
      operationId: GetNWDAFAnalytics
      parameters:
      - description: Identify the analytics.
        explode: true
        in: query
        name: event-id
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
        style: form
      - content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventReportingRequirement'
        description: Identifies the analytics reporting requirement information.
        explode: true
        in: query
        name: ana-req
        required: false
        style: form
      - content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventFilter'
        description: Identify the analytics.
        explode: true
        in: query
        name: event-filter
        required: false
        style: form
      - description: To filter irrelevant responses related to unsupported features
        explode: true
        in: query
        name: supported-features
        required: false
        schema:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
        style: form
      - content:
          application/json:
            schema:
              $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/TargetUeInformation
        description: Identify the target UE information.
        explode: true
        in: query
        name: tgt-ue
        required: false
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyticsData'
          description: Containing the analytics with parameters as relevant for the
            requesting NF service consumer.
        "204":
          description: No Content (The request NWDAF Analytics data does not exist)
        "400":
          $ref: ./TS29571_CommonData.yaml#/components/responses/400
        "401":
          $ref: ./TS29571_CommonData.yaml#/components/responses/401
        "403":
          $ref: ./TS29571_CommonData.yaml#/components/responses/403
        "404":
          content:
            application/problem+json:
              schema:
                $ref: ./TS29571_CommonData.yaml#/components/schemas/ProblemDetails
          description: Indicates that the NWDAF Analytics resource does not exist.
        "406":
          $ref: ./TS29571_CommonData.yaml#/components/responses/406
        "414":
          $ref: ./TS29571_CommonData.yaml#/components/responses/414
        "429":
          $ref: ./TS29571_CommonData.yaml#/components/responses/429
        "500":
          $ref: ./TS29571_CommonData.yaml#/components/responses/500
        "503":
          $ref: ./TS29571_CommonData.yaml#/components/responses/503
        default:
          $ref: ./TS29571_CommonData.yaml#/components/responses/default
      summary: Read a NWDAF Analytics
      tags:
      - NWDAF Analytics (Document)
components:
  schemas:
    AnalyticsData:
      example:
        sliceLoadLevelInfos:
        - '{}'
        - '{}'
        ueComms:
        - '{}'
        - '{}'
        timeStampGen: '{}'
        start: '{}'
        nfLoadLevelInfos:
        - '{}'
        - '{}'
        svcExps:
        - '{}'
        - '{}'
        nsiLoadLevelInfos:
        - '{}'
        - '{}'
        userDataCongInfos:
        - '{}'
        - '{}'
        abnorBehavrs:
        - '{}'
        - '{}'
        nwPerfs:
        - '{}'
        - '{}'
        ueMobs:
        - '{}'
        - '{}'
        expiry: '{}'
        qosSustainInfos:
        - '{}'
        - '{}'
        suppFeat: '{}'
      properties:
        start:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/DateTime
        expiry:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/DateTime
        timeStampGen:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/DateTime
        sliceLoadLevelInfos:
          description: The slices and their load level information.
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/SliceLoadLevelInformation
          minItems: 1
          type: array
        nsiLoadLevelInfos:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/NsiLoadLevelInfo
          minItems: 1
          type: array
        nfLoadLevelInfos:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/NfLoadLevelInformation
          minItems: 1
          type: array
        nwPerfs:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/NetworkPerfInfo
          minItems: 1
          type: array
        svcExps:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/ServiceExperienceInfo
          minItems: 1
          type: array
        qosSustainInfos:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/QosSustainabilityInfo
          minItems: 1
          type: array
        ueMobs:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/UeMobility
          minItems: 1
          type: array
        ueComms:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/UeCommunication
          minItems: 1
          type: array
        userDataCongInfos:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/UserDataCongestionInfo
          minItems: 1
          type: array
        abnorBehavrs:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/AbnormalBehaviour
          minItems: 1
          type: array
        suppFeat:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
      type: object
    EventFilter:
      not:
        required:
        - anySlice
        - snssais
      properties:
        anySlice:
          $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/AnySlice
        snssais:
          description: Identification(s) of network slice to which the subscription
            belongs.
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/Snssai
          minItems: 1
          type: array
        appIds:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/ApplicationId
          minItems: 1
          type: array
        dnns:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/Dnn
          minItems: 1
          type: array
        dnais:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/Dnai
          minItems: 1
          type: array
        networkArea:
          $ref: ./TS29554_Npcf_BDTPolicyControl.yaml#/components/schemas/NetworkAreaInfo
        nfInstanceIds:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/NfInstanceId
          minItems: 1
          type: array
        nfSetIds:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/NfSetId
          minItems: 1
          type: array
        nfTypes:
          items:
            $ref: ./TS29510_Nnrf_NFManagement.yaml#/components/schemas/NFType
          minItems: 1
          type: array
        nsiIdInfos:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/NsiIdInfo
          minItems: 1
          type: array
        qosRequ:
          $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/QosRequirement
        nwPerfTypes:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/NetworkPerfType
          minItems: 1
          type: array
        bwRequs:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/BwRequirement
          minItems: 1
          type: array
        excepIds:
          items:
            $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/ExceptionId
          minItems: 1
          type: array
        exptAnaType:
          $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/ExpectedAnalyticsType
        exptUeBehav:
          $ref: ./TS29503_Nudm_SDM.yaml#/components/schemas/ExpectedUeBehaviourData
      type: object
    EventId:
      anyOf:
      - enum:
        - LOAD_LEVEL_INFORMATION
        - NETWORK_PERFORMANCE
        - NF_LOAD
        - SERVICE_EXPERIENCE
        - UE_MOBILITY
        - UE_COMMUNICATION
        - QOS_SUSTAINABILITY
        - ABNORMAL_BEHAVIOUR
        - USER_DATA_CONGESTION
        - NSI_LOAD_LEVEL
        type: string
      - description: |
          This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
        type: string
      description: |
        Possible values are - LOAD_LEVEL_INFORMATION: Represent the analytics of load level information of corresponding network slice. - NETWORK_PERFORMANCE: Represent the analytics of network performance information. - NF_LOAD: Indicates that the event subscribed is NF Load. - SERVICE_EXPERIENCE: Represent the analytics of service experience information of the specific applications. - UE_MOBILITY: Represent the analytics of UE mobility. - UE_COMMUNICATION: Represent the analytics of UE communication. - QOS_SUSTAINABILITY: Represent the analytics of QoS sustainability information in the certain area.  - ABNORMAL_BEHAVIOUR: Indicates that the event subscribed is abnormal behaviour information. - USER_DATA_CONGESTION: Represent the analytics of the user data congestion in the certain area. - NSI_LOAD_LEVEL: Represent the analytics of Network Slice and the optionally associated Network Slice Instance.
    NwdafFailureCode:
      anyOf:
      - enum:
        - UNAVAILABLE_DATA
        type: string
      - description: |
          This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
        type: string
      description: |
        Possible values are
          - UNAVAILABLE_DATA: Indicates the requested statistics information for the event is rejected since necessary data to perform the service is unavailable.
    EventReportingRequirement:
      properties:
        accuracy:
          $ref: ./TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/Accuracy
        startTs:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/DateTime
        endTs:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/DateTime
        sampRatio:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/SamplingRatio
        maxObjectNbr:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/Uinteger
        maxSupiNbr:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/Uinteger
        timeAnaNeeded:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/DateTime
      type: object
    Accuracy:
      anyOf:
      - enum:
        - LOW
        - HIGH
        type: string
      - description: |
          This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
        type: string
      description: |
        Possible values are - LOW: Low accuracy. - HIGH: High accuracy.
  securitySchemes:
    oAuth2ClientCredentials:
      flows:
        clientCredentials:
          scopes:
            nnwdaf-analyticsinfo: Access to the Nnwdaf_AnalyticsInfo API
          tokenUrl: '{nrfApiRoot}/oauth2/token'
      type: oauth2
