/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
)

// Linger please
var (
	_ _context.Context
)

// NWDAFEventsSubscriptionsCollectionApiService NWDAFEventsSubscriptionsCollectionApi service
type NWDAFEventsSubscriptionsCollectionApiService service

type ApiCreateNWDAFEventsSubscriptionRequest struct {
	ctx _context.Context
	ApiService *NWDAFEventsSubscriptionsCollectionApiService
	nnwdafEventsSubscription *NnwdafEventsSubscription
}

func (r ApiCreateNWDAFEventsSubscriptionRequest) NnwdafEventsSubscription(nnwdafEventsSubscription NnwdafEventsSubscription) ApiCreateNWDAFEventsSubscriptionRequest {
	r.nnwdafEventsSubscription = &nnwdafEventsSubscription
	return r
}

func (r ApiCreateNWDAFEventsSubscriptionRequest) Execute() (NnwdafEventsSubscription, *_nethttp.Response, GenericOpenAPIError) {
	return r.ApiService.CreateNWDAFEventsSubscriptionExecute(r)
}

/*
 * CreateNWDAFEventsSubscription Create a new Individual NWDAF Events Subscription
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiCreateNWDAFEventsSubscriptionRequest
 */
func (a *NWDAFEventsSubscriptionsCollectionApiService) CreateNWDAFEventsSubscription(ctx _context.Context) ApiCreateNWDAFEventsSubscriptionRequest {
	return ApiCreateNWDAFEventsSubscriptionRequest{
		ApiService: a,
		ctx: ctx,
	}
}

/*
 * Execute executes the request
 * @return NnwdafEventsSubscription
 */
func (a *NWDAFEventsSubscriptionsCollectionApiService) CreateNWDAFEventsSubscriptionExecute(r ApiCreateNWDAFEventsSubscriptionRequest) (NnwdafEventsSubscription, *_nethttp.Response, GenericOpenAPIError) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		executionError       GenericOpenAPIError
		localVarReturnValue  NnwdafEventsSubscription
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NWDAFEventsSubscriptionsCollectionApiService.CreateNWDAFEventsSubscription")
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, nil, executionError
	}

	localVarPath := localBasePath + "/subscriptions"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.nnwdafEventsSubscription == nil {
		executionError.error = "nnwdafEventsSubscription is required and must be specified"
		return localVarReturnValue, nil, executionError
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.nnwdafEventsSubscription
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, nil, executionError
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		executionError.error = err.Error()
		return localVarReturnValue, localVarHTTPResponse, executionError
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, localVarHTTPResponse, executionError
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, executionError
}
